// Code generated by gosx. DO NOT EDIT.
package modules

import (
	_ "github.com/m31-labs/rostrum/app"
	_ "github.com/m31-labs/rostrum/app/organizer"
	_ "github.com/m31-labs/rostrum/app/organizer/agenda"
	_ "github.com/m31-labs/rostrum/app/organizer/communications"
	_ "github.com/m31-labs/rostrum/app/organizer/embeds"
	_ "github.com/m31-labs/rostrum/app/organizer/forms"
	_ "github.com/m31-labs/rostrum/app/organizer/integrations"
	_ "github.com/m31-labs/rostrum/app/organizer/portal"
	_ "github.com/m31-labs/rostrum/app/organizer/review"
	_ "github.com/m31-labs/rostrum/app/organizer/settings"
	_ "github.com/m31-labs/rostrum/app/organizer/speakers"
	_ "github.com/m31-labs/rostrum/app/organizer/submissions"
	_ "github.com/m31-labs/rostrum/app/portal"
	_ "github.com/m31-labs/rostrum/app/public"
	_ "github.com/m31-labs/rostrum/app/review"
	_ "github.com/m31-labs/rostrum/app/submit"
)
